[package]
name = "slice-n-dice-server"
version = "0.1.0"
authors = ["Tim Dévé <TimDeve@users.noreply.github.com>"]
edition = "2018"

[dependencies]
anyhow    = "1"
async-std = { version = "1", features = ["attributes"] }
serde     = "1"
sqlx      = { version = "0.5", features = ["runtime-async-std-native-tls", "postgres", "migrate", "time", "uuid"] }
uuid      = { version = "0.8", features = ["serde"] }
tide      = "0.16"
time      = "0.2"
rand      = "0.8"

