#!/usr/bin/env bash

foodStuff=(Salad Fish Rice Spaghetti Pizza Hamburger Eggs Cheese Sausages Apple Grape Milk Candy Cookie Pie Cake Cupcake)
foodStuffLength=${#foodStuff[@]}

NEW_LINE=$'\n'

query=""

function genRecipes() {
  local isQuick="$1"

  for _ in {1..20}; do
    foodName=""
    for i in {1..3}; do
      maxIndex=$((foodStuffLength - 1))
      foodIndex=$((0 + RANDOM % maxIndex))

      whiteSpace=' '
      if [[ $i = 3 ]]; then
        whiteSpace=''
      fi
      foodName="$foodName${foodStuff[$foodIndex]}$whiteSpace"
    done

    query="${query}INSERT INTO recipes (name, quick) VALUES ('$foodName', $isQuick);$NEW_LINE"
  done
}

genRecipes true
genRecipes false

psql "$DATABASE_URL" -c "$query"

