#!/usr/bin/env bash

recipeBody=$(jq -c '.blocks[1]=.blocks[0] | .blocks[1].key="dead7"' <<'RECIPE_BODY'
{"blocks":[{"key":"b7ma1","text":"Some recipe thing","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}}],"entityMap":{}}
RECIPE_BODY
)

foodStuff=(Salad Fish Rice Spaghetti Pizza Hamburger Eggs Cheese Sausages Apple Grape Milk Candy Cookie Pie Cake Cupcake)
foodStuffLength=${#foodStuff[@]}

NEW_LINE=$'\n'

query=""

function genRecipes() {
  local isQuick="$1"

  for _ in {1..20}; do
    foodName=""
    for i in {1..3}; do
      maxIndex=$((foodStuffLength - 1))
      foodIndex=$((0 + RANDOM % maxIndex))

      whiteSpace=' '
      if [[ $i = 3 ]]; then
        whiteSpace=''
      fi
      foodName="$foodName${foodStuff[$foodIndex]}$whiteSpace"
    done

    recipeBodyWithName=$(echo "$recipeBody" | jq -c ".blocks[1].text=\"about $foodName\"")
    query="${query}INSERT INTO recipes (name, quick, body) VALUES ('$foodName', $isQuick, '$recipeBodyWithName');$NEW_LINE"
  done
}

genRecipes true
genRecipes false

psql "$DATABASE_URL" -c "$query"

