name: Test and Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: "[Server] Build"
      run: "cd server && make build-dev"

    - name: "[Server] Unit Tests"
      run: "cd server && make test-unit"

    - name: "[Server] Start test DB"
      run: docker compose up integration-db -d

    - name: "[Server] Integration Tests"
      run: "cd server && make test-integration"
      env:
        DATABASE_URL: "postgres://postgres:postgres@localhost:15433"

    - name: "[Server] Stop test DB"
      run: |
        docker compose stop integration-db \
        && docker compose rm integration-db --force

    - name: Build the Docker image
      run: docker build .

